from setuptools import setup, find_packages

setup(
    name="ahy-governance",
    version="0.9.1",
    description="Open-source AI Agent governance: conflict detection, cost control, compliance audit, self-healing. Deploy agents with confidence.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Leo-Ayh-Oday",
    author_email="2115464137@qq.com",
    url="https://github.com/Leo-Ayh-Oday/ahy-governance",
    project_urls={
        "Bug Tracker": "https://github.com/Leo-Ayh-Oday/ahy-governance/issues",
        "Documentation": "https://github.com/Leo-Ayh-Oday/ahy-governance/blob/main/README.md",
        "Source Code": "https://github.com/Leo-Ayh-Oday/ahy-governance",
    },
    keywords=[
        "ai-agents",
        "governance",
        "compliance",
        "multi-agent",
        "agent-orchestration",
        "soc2",
        "audit-logging",
        "cost-tracking",
        "prompt-injection",
        "open-source",
        "python",
        "claude-mcp",
        "langchain",
        "crewai",
    ],
    python_requires=">=3.10",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: System Administrators",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: System :: Monitoring",
        "Topic :: System :: Systems Administration",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
)
